DROP TABLE IF EXISTS spring.user;
DROP TABLE IF EXISTS spring.authority;
DROP TABLE IF EXISTS spring.product;

CREATE TABLE spring.user (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(45) NOT NULL,
  password TEXT NOT NULL,
  algorithm VARCHAR(45) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE spring.authority (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(45) NOT NULL,
  user INT NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE spring.product (
 id INT NOT NULL AUTO_INCREMENT,
 name VARCHAR(45) NOT NULL,
 price VARCHAR(45) NOT NULL,
 currency VARCHAR(45) NOT NULL,
 PRIMARY KEY(id)
);
